[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
minReplicas = 1
maxReplicas = 1

[deploy.envs]
NODE_ENV = "production"
NODE_VERSION = "18.x"
PORT = "3001"
REACT_APP_API_URL = "https://whispra-backend-production.up.railway.app" 