[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node api/index.js"
healthcheckPath = "/test"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production" 