services:
  - type: web
    name: whispra-backend
    env: node
    buildCommand: npm install
    startCommand: node api/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: FRONTEND_URL
        value: https://whispra-nine.vercel.app 